jaeger:
	google-chrome http://localhost:16686
amit:
	curl -X POST http://localhost:6001/gateway -d '{"user_name": "amit"}'
jitendra:
	curl -X POST http://localhost:6001/gateway -d '{"user_name": "jitendra"}'
fail:
	curl -X POST http://localhost:6001/gateway -d '{"user_name": "fail"}'
